<?php
/**
 * Backend Assets
 *
 * @package  TriMS
 * @company  Triangle Mena <http://trianglemena.com>
 * @developer  Maroun Melhem <http://maroun.me>
 * @version 1.0
 *
 */

/**
 * Remove wp update notice
 */
function remove_wp_update_notice()
{
    if (!current_user_can('manage_options')) {
        remove_action('admin_notices', 'update_nag', 3);
    }
}
add_action('admin_init', 'remove_wp_update_notice');


/**
 * Remove wp logo from top bar
 */
function annointed_admin_bar_remove()
{
    global $wp_admin_bar;
    $wp_admin_bar->remove_menu('wp-logo');
}
add_action('wp_before_admin_bar_render', 'annointed_admin_bar_remove', 0);


/**
 * Remove links from admin bar
 */
function remove_admin_bar_links()
{
    global $wp_admin_bar;
    $wp_admin_bar->remove_menu('feedback');         // Remove the feedback link
    $wp_admin_bar->remove_menu('updates');          // Remove the updates link
    $wp_admin_bar->remove_menu('comments');         // Remove the comments link
    $wp_admin_bar->remove_menu('new-content');      // Remove the content link
    $wp_admin_bar->remove_menu('w3tc');             // If you use w3 total cache remove the performance link
}
add_action('wp_before_admin_bar_render', 'remove_admin_bar_links');


/**
 * Remove default dashboard widgets
 */
remove_action('welcome_panel', 'wp_welcome_panel');
function remove_dashboard_widgets()
{
    global $wp_meta_boxes;
    unset($wp_meta_boxes['dashboard']['side']['core']['dashboard_quick_press']);
    unset($wp_meta_boxes['dashboard']['normal']['core']['dashboard_incoming_links']);
    unset($wp_meta_boxes['dashboard']['normal']['core']['dashboard_right_now']);
    unset($wp_meta_boxes['dashboard']['normal']['core']['dashboard_plugins']);
    unset($wp_meta_boxes['dashboard']['normal']['core']['dashboard_recent_drafts']);
    unset($wp_meta_boxes['dashboard']['normal']['core']['dashboard_recent_comments']);
    unset($wp_meta_boxes['dashboard']['side']['core']['dashboard_primary']);
    unset($wp_meta_boxes['dashboard']['side']['core']['dashboard_secondary']);

}
add_action('wp_dashboard_setup', 'remove_dashboard_widgets');

function remove_dashboard_widgets_act(){
    remove_meta_box('dashboard_activity', 'dashboard', 'normal');
}
add_action('wp_dashboard_setup', 'remove_dashboard_widgets_act');


/**
 * Remove help options
 */
function remove_help_tabs($old_help, $screen_id, $screen)
{
    $screen->remove_help_tabs();
    return $old_help;
}

add_filter('contextual_help', 'remove_help_tabs', 999, 3);


/**
 * Set custom dashboard logo url
 */
function custom_loginlogo_url($url)
{
    return "http://trianglemena.com";
}

add_filter('login_headerurl', 'custom_loginlogo_url');


/**
 * Remove admin notices (generated by plugins)
 */
function wphidenag()
{
    remove_action('admin_notices', 'update_nag', 3);
}

add_action('admin_menu', 'wphidenag');


/**
 * Remove the Edit link from the admin bar
 *
 */
function remove_admin_bar_edit_link()
{
    global $wp_admin_bar;
    $wp_admin_bar->remove_menu('edit');
}

add_action('wp_before_admin_bar_render', 'remove_admin_bar_edit_link');


/**
 * Show pages and posts IDs for admins
 */
function revealid_add_id_column($columns)
{
    $columns['revealid_id'] = 'ID';
    return $columns;
}
add_filter('manage_pages_columns', 'revealid_add_id_column', 5);

function revealid_id_column_content($column, $id)
{
    if ('revealid_id' == $column) {
        echo $id;
    }
}
add_action('manage_pages_custom_column', 'revealid_id_column_content', 5, 2);


/**
 * Remove core updates
 */
function remove_core_updates()
{
    global $wp_version;
    return (object)array('last_checked' => time(), 'version_checked' => $wp_version,);
}
add_filter('pre_site_transient_update_core', 'remove_core_updates');
add_filter('pre_site_transient_update_plugins', 'remove_core_updates');
add_filter('pre_site_transient_update_themes', 'remove_core_updates');
add_action('after_setup_theme', 'remove_core_updates');
remove_action('load-update-core.php', 'wp_update_plugins');
add_filter('pre_site_transient_update_plugins', '__return_null');


/**
 * Remove core updates
 */
function login_logo_url_title() {
    return 'TriMS';
}
add_filter( 'login_headertitle', 'login_logo_url_title' );


/**
 * Set default admin color scheme
 */
function change_admin_color($result)
{
    return 'default';
}
add_filter('get_user_option_admin_color', 'change_admin_color');

/**
 * Change Howdy text
 */
add_filter('gettext', 'change_howdy', 10, 3);
function change_howdy($translated, $text, $domain) {

    if (!is_admin() || 'default' != $domain)
        return $translated;

    if (false !== strpos($translated, 'Howdy'))
        return str_replace('Howdy', 'Welcome', $translated);

    return $translated;
}

function tinymce_bidi_addbuttons() {
    if( !current_user_can ( 'edit_posts' ) && !current_user_can ( 'edit_pages' ) ) {
        return;
    }
    if( get_user_option ( 'rich_editing' ) == 'true' ) {
        add_filter( "mce_external_plugins", "tinymce_bidi_plugin" );
        add_filter( "mce_buttons", "tinymce_bidi_buttons" );
    }
}
add_action( "init", "tinymce_bidi_addbuttons" );

/*Add RTL to tinyMCE*/
function tinymce_bidi_buttons($buttons) {
    array_push($buttons, "separator", "ltr", "rtl");
    return $buttons;
}

function tinymce_bidi_plugin($plugin_array) {
    if (get_bloginfo('version') < 3.9) {
        $plugin_array['directionality'] = includes_url('js/tinymce/plugins/directionality/editor_plugin.js');
    } else {
        $plugin_array['directionality'] = includes_url('js/tinymce/plugins/directionality/plugin.min.js');
    }
    return $plugin_array;
}


/*Add favicon to admin*/
function trims_add_favicon() {
    $favicon_path = get_site_url() . '/favicon.ico';
    echo '<link rel="shortcut icon" href="' . $favicon_path . '" />';
}
add_action( 'admin_head', 'trims_add_favicon' );


/*Add authors filter to edit page*/
function trims_filter_by_the_author() {
    $params = array(
        'name' => 'author',
        'show_option_all' => 'All Authors'
    );

    if ( isset($_GET['user']) )
        $params['selected'] = $_GET['user'];

    wp_dropdown_users( $params );
}

add_action('restrict_manage_posts', 'trims_filter_by_the_author');

/*Move yoast meta box to bottom*/
function yoasttobottom() {
    return 'low';
}
add_filter( 'wpseo_metabox_prio', 'yoasttobottom');